export const ADD_TO_CART = "ADD_TO_CART";
export const INCREMENT_ITEM_QUANTITY = "INCREMENT_ITEM_QUANTITY";
export const DECREMENT_ITEM_QUANTITY = "DECREMENT_ITEM_QUANTITY";
export const DELETE_ITEM = "DELETE_ITEM";
