export const REQUEST_GET_PRODUCTS = "REQUEST_GET_PRODUCTS";
export const SUCCESS_GET_PRODUCTS = "SUCCESS_GET_PRODUCTS";
export const FAILED_GET_PRODUCTS = "FAILED_GET_PRODUCTS";

export const REQUEST_GET_POPULAR_PRODUCTS = "REQUEST_GET_POPULAR_PRODUCTS";
export const SUCCESS_GET_POPULAR_PRODUCTS = "SUCCESS_GET_POPULAR_PRODUCTS";
export const FAILED_GET_POPULAR_PRODUCTS = "FAILED_GET_POPULAR_PRODUCTS";

export const MODIFY_ITEM = "MODIFY_ITEM";
