export const REQUEST_AUTH_LOGIN = "REQUEST_AUTH_LOGIN";
export const SUCCESS_AUTH_LOGIN = "SUCCESS_AUTH_LOGIN";
export const FAILED_AUTH_LOGIN = "FAILED_AUTH_LOGIN";

export const AUTH_SIGN_OUT = "AUTH_SIGN_OUT";
