export const REQUEST_AUTH_LOGIN = "REQUEST_AUTH_LOGIN";
export const SUCCESS_AUTH_LOGIN = "SUCCESS_AUTH_LOGIN";
export const FAILED_AUTH_LOGIN = "FAILED_AUTH_LOGIN";

export const REQUEST_AUTH_REGISTER = "REQUEST_AUTH_REGISTER";
export const SUCCESS_AUTH_REGISTER = "SUCCESS_AUTH_REGISTER";
export const FAILED_AUTH_REGISTER = "FAILED_AUTH_REGISTER";

export const REQUEST_GET_USER = "REQUEST_GET_USER";
export const SUCCESSFULLY_GET_USER = "SUCCESSFULLY_GET_USER";
export const FAILED_GET_USER = "FAILED_GET_USER";

export const AUTH_SIGN_OUT = "AUTH_SIGN_OUT";
export const ADD_ADDRESS = "ADD_ADDRESS";
export const SET_ACTIVE_ADDRESS = "SET_ACTIVE_ADDRESS";
export const DELETE_ADDRESS = "DELETE_ADDRESS";

export const REQUEST_REFRESH_ORDERS = "REQUEST_REFRESH_ORDERS";
export const SUCCESS_REFRESH_ORDERS = "SUCCESS_REFRESH_ORDERS";
export const FAILED_REFRESH_ORDERS = "FAILED_REFRESH_ORDERS";

export const ADD_ORDER = "ADD_ORDER";
