export const REQUEST_GET_SHOPS = "REQUEST_GET_SHOPS";
export const SUCCESS_GET_SHOPS = "SUCCESS_GET_SHOPS";
export const FAILED_GET_SHOPS = "FAILED_GET_SHOPS";

export const REQUEST_FETCH_PRODUCTS = "REQUEST_FETCH_PRODUCTS";
export const SUCCESS_FETCH_PRODUCTS = "SUCCESS_FETCH_PRODUCTS";
export const FAILED_FETCH_PRODUCTS = "FAILED_FETCH_PRODUCTS";
